OldSourceCode/Foley/SmartMFGFoley/WebApp/ViewModels/PODetailViewModel.cs
using DataLibrary.Models;
using System.Collections.Generic;

namespace WebApp.ViewModels
{
    public class PODetailViewModel
    {       
        public long Document_Nbr { get; set; }     
        public string Supplier_Name { get; set; }      
        public string Supplier_Nbr { get; set; }

        public string MaterialDesc { get; set; }

        public List<InboundRawMaterialsModel> ItemList { get; set; }

    }
}

OldSourceCode/Foley/SmartMFGFoley/WebApp/Controllers/RawMaterialController.cs
using DataLibrary.DataAccess.Abstract;
using DataLibrary.Models;
using DataLibrary.Processors.Abstract;
using DataLibrary.Processors.Sql;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Transactions;
using WebApp.Common;
using WebApp.Common.Services.Abstract;
using WebApp.ViewModels;
using WebApp.Models.Services;

namespace WebApp.Controllers
{
    public class RawMaterialController : Controller
    {
        private readonly IRawMaterialProcessor _RMProcessor;
        private readonly IReadWriteDataAccess _readWriteAccess;
        private readonly IInboundRawMaterialsProcessor _rawMaterialProcessor;
        private readonly ISapMatlMasterProcessor _sapMaterialProcessor;
        private readonly IConfiguration _config;
        private readonly ILimsService _lims;
        private readonly ILogger<RawMaterialController> _logger;
        private readonly IRawMaterialsService _rawMaterialsService;

        public RawMaterialController(IRawMaterialProcessor labelProcessor,
            IReadWriteDataAccess readWriteAccess,
            IInboundRawMaterialsProcessor rawMaterialProcessor,
            ISapMatlMasterProcessor sapMaterialProcessor,
            IConfiguration config,
            ILimsService lims,
            ILogger<RawMaterialController> logger,
            IRawMaterialsService rawMaterialsService)
        {
            _RMProcessor = labelProcessor;
            _readWriteAccess = readWriteAccess;
            _rawMaterialProcessor = rawMaterialProcessor;
            _sapMaterialProcessor = sapMaterialProcessor;
            _config = config;
            _lims = lims;
            _logger = logger;
            _rawMaterialsService = rawMaterialsService;
        }
        // GET: RawMaterialController
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult PurchaseOrderLabel(long id)
        {
            RawMaterialViewModel lblVm = new RawMaterialViewModel();
            try
            {
                //bool POAutoLabelCreation = false;
                RawMaterialDetailModel irm = _rawMaterialProcessor.GetRawMaterialByRawMatlId(id);
                IEnumerable<PurchaseOrderLabelsModel> labelList = _RMProcessor.GetLabelsByRawMtlsIdAll(irm?.Ib_Raw_Mtls_Id).OrderByDescending(v => v.Label_Id); ;
                IEnumerable<PurchaseOrderLabelsModel> labelListChilds = labelList.Where(x => x.Bag_No != 0);
                labelList = labelList.Where(x => x.Bag_No == 0);
                var sapMaterial = _sapMaterialProcessor.GetSapMaterialByMATLNBR(irm?.Matl_Nbr);
                lblVm.Ibr = irm;
                lblVm.Sapm = sapMaterial;
                bool IsPackagingMaterial = (sapMaterial?.Sap_Matl_Type?.ToUpper() == AppSettings.GetPackagingMaterialValue()) ? true : false;

                ViewData["Labels_CSV_ALL"] = "";
                ViewData["Labels_CSV_ALL"] = String.Join(",", labelList.Where(x => x.Label_Scan_Date == null || x.Delivery_Scan_Date == null).ToList().Select(x => x.Label_Id.ToString()).ToArray());


                //if(irm.FRM.ToLower() == "im" && irm.Too.ToLower() == "im" && !string.IsNullOrEmpty(sapMaterial.BATCH_MANAGED) && sapMaterial.BATCH_MANAGED =="0")

                bool disabled = false;
                bool AllScanned = true;

                //if (irm.FRM.ToLower() == "im" && irm.Too.ToLower() == "im")
                //{
                //    if (labelList.Count() < 1)
                //    {
                //        List<string> arr = new List<string>();
                //        arr.Add(irm.Ib_Raw_Mtls_Id.ToString()); //0 Material Id
                //        arr.Add(DateTime.Now.ToString()); //1 Product Received Date
                //        arr.Add(irm.Quantity.ToString()); //2 Amount Received
                //        arr.Add(irm.Lot_Nbr?.ToString()); //3 Lot Number
                //        arr.Add("1"); //4 total Bag Number
                //        arr.Add(null); //5 Vendor Batch
                //        arr.Add(null); //6 Country of origin
                //        arr.Add("1"); //7 Pallent Number
                //        arr.Add(irm.Ib_Raw_Mtls_Id.ToString()); //8 PO Number
                //        arr.Add(irm.Matl_Nbr.ToString()); //9 Material Number
                //        arr.Add(null); //10 Bill of Lading
                //        arr.Add(null); //11 Note
                //        arr.Add(IsPackagingMaterial.ToString()); //12 IsPackaging Material
                //        arr.Add(irm.Uom); //13 UOM
                //        arr.Add(irm.Supplier_Nbr); //14
                //        CreateLabel(arr.ToArray());


                //        labelList = _RMProcessor.GetLabelsByRawMtlsIdAll(irm?.Ib_Raw_Mtls_Id).OrderByDescending(v => v.Label_Id); ;
                //        labelListChilds = labelList.Where(x => x.Bag_No != 0);
                //        labelList = labelList.Where(x => x.Bag_No == 0);
                //        POAutoLabelCreation = true;
                //    }
                //    else
                //    {
                //        POAutoLabelCreation = true;
                //    }
                //}





                decimal sumAmount = 0;
                decimal scannedAmountTotal = 0;
                if (labelList.Count() > 0)
                {
                    var sapDate = labelList.OrderByDescending(l => l.Sent_Sap_Date).FirstOrDefault();
                    var sapNotSent = labelList.Where(l => l.Sent_Sap_Date == null);
                    lblVm.SapSentDate = sapDate?.Sent_Sap_Date;
                    var labelScanned = labelList.Where(l => l.Label_Scan_Date == null);
                    if (IsPackagingMaterial)
                    {
                        disabled = (sapNotSent.Count() > 0) ? false : true;
                        AllScanned = true;
                        scannedAmountTotal = labelList.Sum(n => (n.Uom == irm.Uom ? n.Amt_Received : (n.Uom == "KG" && irm.Uom == "LB" ? KG_to_LB(n.Amt_Received) : (n.Uom == "LB" && irm.Uom == "KG" ? LB_to_KG(n.Amt_Received) : n.Amt_Received))));
                    }
                    else
                    {
                        if (labelScanned.Count() > 0)
                            disabled = true;
                        else
                            disabled = (sapNotSent.Count() > 0) ? false : true;
                        AllScanned = (labelList.Where(x => x.Label_Scan_Date == null).Count() > 0 ? false : true);
                        scannedAmountTotal = labelList.Where(l => l.Label_Scan_Date != null).Sum(n => (n.Uom == irm.Uom ? n.Amt_Received : (n.Uom == "KG" && irm.Uom == "LB" ? KG_to_LB(n.Amt_Received) : (n.Uom == "LB" && irm.Uom == "KG" ? LB_to_KG(n.Amt_Received) : n.Amt_Received))));
                    }

                    foreach (var rec in labelList)
                    {
                        sumAmount += (rec.Uom == irm.Uom ? rec.Amt_Received : (rec.Uom == "KG" && irm.Uom == "LB" ? KG_to_LB(rec.Amt_Received) : (rec.Uom == "LB" && irm.Uom == "KG" ? LB_to_KG(rec.Amt_Received) : rec.Amt_Received)));
                        string lineItem = "";
                        foreach (var item in labelListChilds.Where(x => x.Label_Id == rec.Label_Id))
                        {
                            if (item != null)
                            {
                                //item.Amt_Received = (item.TotalNoofPallets.ToString() != null && item.TotalNoofPallets.ToString() != "" && item.TotalNoofPallets > 0) ? (item.Uom == "KG" && item.Uom == "LB" ? KG_to_LB((item.Amt_Received / item.TotalNoofPallets)) : LB_to_KG((item.Amt_Received / item.TotalNoofPallets))) : (item.Uom == "KG" && item.Uom == "LB" ? KG_to_LB((item.Amt_Received Pallets)) : LB_to_KG((item.Amt_Received)));
                                // item.Amt_Received = (item.TotalNoofPallets.ToString() != null && item.TotalNoofPallets.ToString() != "" && item.TotalNoofPallets > 0) ? (item.Amt_Received / item.TotalNoofItemsPerPallets) : item.Amt_Received;
                                lineItem += item.Label_Id + "|" + (item.Uom == irm.Uom ? item.Amt_Received : (item.Uom == "KG" && irm.Uom == "LB" ? KG_to_LB(item.Amt_Received) : (item.Uom == "LB" && irm.Uom == "KG" ? LB_to_KG(item.Amt_Received) : item.Amt_Received))) + " " + item.Uom + "|"
                                    + item.Bag_No + "|" + item.Batch_Id + "|"
                                    + item.Product_Received_Date + "| " + item.Label_Print_Date + "|"
                                    + item.Label_Scan_Date + "~";
                            }
                        }
                        rec.LineItems = lineItem;
                    }
                }
                else
                {
                    disabled = true;
                }


                //if (POAutoLabelCreation)
                //{
                //    AllScanned = true;
                //}
                lblVm.Polabels = labelList;
                lblVm.PoLablesAmount = sumAmount;
                lblVm.ScannedAmount = scannedAmountTotal;
                lblVm.AllScanned = true;

                lblVm.Completed = scannedAmountTotal < irm?.Quantity ? false : true;
                lblVm.disabled = disabled;
                lblVm.PackingMaterial = IsPackagingMaterial;

            }
            catch (Exception ex)
            {
                _logger.LogError("Error for PurchaseOrderLabel of RawMaterialController: " + ex.Message);
            }

            return View(lblVm);
        }

        public JsonResult SendPOToSAP(string itemId)
        {
            bool blnSuccess = false;
            if (!string.IsNullOrEmpty(itemId))
            {
                try
                {

OldSourceCode/Foley/SmartMFGFoley/WebApp/Views/InboundRawMaterials/Index.cshtml
@model WebApp.ViewModels.RawMaterialsGroupedViewModel
@{
    ViewBag.Title = ViewBag.TitlePart;
}

<div class="apm-filters" id="" style="float:right;">
    <div class="apm-icon-key key-icon-con" id="tool_icon" style=" width: auto; height: auto;">
        <i onclick="$('#export-filters').toggle();$('#export-filter-icon').toggle();" id="export-filter-icon" class="showapppopup1 fas fa-tools apm-icon"></i>
        <div id="export-filters" class="showapppopup" style="display:none;border-radius:unset!important;padding:1rem;">
            <i onclick="$('#export-filters').toggle();$('#export-filter-icon').toggle();" class="showapppopup1 fas fa-tools apm-icon"></i>
            <span onclick="$('#export-filters').toggle();$('#export-filter-icon').toggle();">Tools</span>
            <div class="dropdown-divider"></div>
            <button type="button" id="ExportExcelPO" class="btn apm-label"><i class='fa fa-download'></i>Download Excel</button>
        </div>
    </div>
</div>
<partial name="_NavLinks" />
<br />
<br />
<br />
<main class="apm-main">
    
    <br /><div id='spinner' class='collapse'><i class='fas fa-spinner fa-spin fa-4x'></i></div>
    <div>
        <table id="RawMats" class="table table-bordered table-hover table-sm collapse" style="width:100%">
            <thead>
                <tr>
                    <th>PO Number</th>
                    <th>Document Type</th>
                    <th>Material Type</th>
                    <th>Supplier Name</th>
                    <th>Supplier Number</th>
                    <th style="display:none;" class="noprint">LineItem</th>
                    <th>SAP Sent</th>
                    <th style="display:none;">Quantity</th>
                    <th style="display:none;">Quantity Received</th>
                </tr>
            </thead>
            <tbody>
                <tr style="display:none;">
                    <th>PO Number</th>
                    <th>Document Type</th>
                    <th>Material Type</th>
                    <th>Supplier Name</th>
                    <th>Supplier Number</th>
                    <th style="display:none;" class="noprint">LineItem</th>
                    <th>SAP Sent</th>
                    <th style="display:none;">Quantity</th>
                    <th style="display:none;">Quantity Received</th>
                </tr>
                @{
                    foreach (var item in Model.PurchaseOrderList)
                    {
                        <tr>
                            <td class="details-control">
                                @item.POMaterial.Document_Nbr
                            </td>

                            <td @item.Style> @item.POMaterial.Document_Type</td>
                            <td>@item.POMaterial.Sap_Matl_Type @item.POMaterial.Matl_type_descr  @item.POMaterial.Additional_info</td>
                            <td>
                                @item.POMaterial.Supplier_Name
                            </td>
                            <td>
                                @item.POMaterial.Supplier_Nbr
                            </td>
                           
                            <td style="display:none;" class="noprint">@item.LineItems</td>
                            <td>
                                @(item.POMaterial.SENT_TO_SAP>0?"Yes":"No")
                            </td>
                            <td style="display:none;">
                                @item.POMaterial.Quantity.ToString("00.000")
                            </td>
                            <td style="display:none;">
                                @item.POMaterial.Amt_Received.ToString("00.000")
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</main>


@section Scripts {
    <link href="~/js/DataTables/DataTables-1.10.23/css/buttons.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/js/DataTables/DataTables-1.10.23/css/dataTables.bootstrap4.min.css" />
    <script type="text/javascript" src="~/js/DataTables/DataTables-1.10.23/js/jquery.dataTables.min.js"></script>
    <script src="~/js/DataTables/DataTables-1.10.23/js/dataTables.buttons.min.js"></script>
    <script src="~/js/DataTables/DataTables-1.10.23/js/jszip.min.js"></script>
    <script src="~/js/DataTables/DataTables-1.10.23/js/pdfmake.min.js"></script>
    <script src="~/js/DataTables/DataTables-1.10.23/js/vfs_fonts.js"></script>
    <script src="~/js/DataTables/DataTables-1.10.23/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="~/js/DataTables/DataTables-1.10.23/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="~/js/view/RawMaterialTable.js" asp-append-version="true"></script>
}

OldSourceCode/Foley/SmartMFGFoley/WebApp/Views/InboundRawMaterials/PODetails.cshtml
@model WebApp.ViewModels.PODetailViewModel
@{
    ViewBag.Title = "Raw Materials Receiving";
}
<partial name="_NavLinks" />
<br />
<div class="container-fluid">
    <div class="apm-pagenav">
        <a title="Back To PO List" asp-action="Index">Back To PO List</a>
    </div>

    <div class="row my-3">
        <div class="blue-card-screen ">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <text id="POLabel-title">Purchase Order Detail</text>
                    </div>
                    <div class="card-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <span class="font-weight-bold">Document Number</span><br />
                                        @Html.DisplayFor(model => model.Document_Nbr)
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <span class="font-weight-bold">
                                            Supplier Name
                                        </span><br />
                                        @Html.DisplayFor(model => model.Supplier_Name)
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <span class="font-weight-bold">
                                            Supplier Number
                                        </span><br />
                                        @Html.DisplayFor(model => model.Supplier_Nbr)
                                    </div>
                                </div>
                                <div class="col-sm-12 col-md-6 col-lg-3">
                                    <div class="form-group">
                                        <span class="font-weight-bold">
                                            Material Description
                                        </span><br />
                                        @Html.DisplayFor(model => model.MaterialDesc)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="apm-card-footer" id="POLabel-footer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="apm-table-blue">
        <table id="rawMats" class="table table-bordered table-hover table-sm">
            <thead>
                <tr>
                    <th style="text-align:center">Item Number</th>
                    <th style="text-align:center">Material Number</th>
                    <th style="text-align:center">Material Description</th>
                    <th style="text-align:center">QTY</th>
                </tr>
            </thead>
            <tbody id="searchTable">
                @{
                    foreach (var item in Model.ItemList)
                    {
                        <tr onclick="location.href = '@(Url.Action("PurchaseOrderLabel", "RawMaterial", new { id = item.Ib_Raw_Mtls_Id }))'">
                            <td>
                                @item.Item_Nbr
                            </td>
                            <td>
                                @item.Matl_Nbr
                            </td>
                            <td>
                                @Model.MaterialDesc
                            </td>
                            <td>
                                @string.Format("{0:n0}", item.Quantity)  @item.Uom
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>

</div>