OldSourceCode/SmartMFGFoley/WebApp/Controllers/InboundRawMaterialsController.cs
using DataLibrary.Models;
using DataLibrary.Processors.Abstract;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using WebApp.ViewModels;


namespace WebApp.Controllers
{
    public class InboundRawMaterialsController : Controller
    {
        private readonly IInboundRawMaterialsProcessor _rawMaterialProcessor;
        private readonly ISapMatlMasterProcessor _sapMaterialProcessor;
        private readonly IRawMaterialProcessor _poLabelProcessor;


        public InboundRawMaterialsController(IInboundRawMaterialsProcessor rawMaterialProcessor, ISapMatlMasterProcessor sapMaterialProcessor, IRawMaterialProcessor poLabelProcessor)
        {
            _rawMaterialProcessor = rawMaterialProcessor;
            _sapMaterialProcessor = sapMaterialProcessor;
            _poLabelProcessor = poLabelProcessor;
        }

        [Route("RawMaterialReceiving/{rmType?}")]
        public IActionResult Index(string rmType)
        {

            ViewBag.TitlePart = (!String.IsNullOrEmpty(rmType)) ? /*" - " +*/ rmType.Replace("_", " ") : "";
            List<POMaterialModel> POList = (!String.IsNullOrEmpty(rmType)) ? _rawMaterialProcessor.GetRawMaterialByDocType(rmType.Substring(0, 1)) : _rawMaterialProcessor.GetAllSTO();
            POList.Add(new POMaterialModel { Document_Nbr = 0 });   //for not missing last record      

            List<RawMaterialChildViewModel> modelList = new List<RawMaterialChildViewModel>();
            long testNbr = POList[0].Document_Nbr;
            decimal qty = 0;
            string itemStr = "";
            long docNbr = 0;
            int senttosap = 0;
            string supName = "";
            string supNo = "";
            string maDesc = "";
            string maType = "";
            string docType = "";
            string matTypeDesc = "";
            string matAdditionalInfo = "";
            decimal amtReceived = 0;
            decimal TotalamtReceived = 0;

            DateTime? deliveryDate = null;
            foreach (var rec in POList)
            {
                if (testNbr != rec.Document_Nbr)
                {
                    RawMaterialChildViewModel childVM = new RawMaterialChildViewModel();
                    POMaterialModel po = new POMaterialModel();
                    po.Document_Nbr = docNbr;
                    po.Supplier_Name = supName;
                    po.Supplier_Nbr = supNo;
                    po.Quantity = qty;
                    po.Amt_Received = TotalamtReceived;
                    po.Sap_Matl_Descr = maDesc;
                    po.Sap_Matl_Type = maType;
                    po.Matl_type_descr = matTypeDesc;
                    po.Additional_info = matAdditionalInfo;
                    po.Document_Type = docType;
                    po.Requested_Delivery_Date = deliveryDate;
                    po.SENT_TO_SAP = senttosap;
                    childVM.POMaterial = po;
                    if (docType.ToLower() == "po")
                        childVM.Style = " class=internal ";
                    else
                        childVM.Style = "";

                    childVM.LineItems = itemStr;
                    modelList.Add(childVM);
                    qty = 0;
                    TotalamtReceived = 0;
                    itemStr = "";
                }

                docNbr = rec.Document_Nbr;
                supName = rec.Supplier_Name;
                supNo = rec.Supplier_Nbr;
                maDesc = rec.Sap_Matl_Descr;
                maType = rec.Sap_Matl_Type;
                docType = rec.Document_Type;
                matTypeDesc = rec.Matl_type_descr;
                matAdditionalInfo = rec.Additional_info;
                deliveryDate = rec.Requested_Delivery_Date;
                amtReceived = rec.Amt_Received;

                if (rec.Frm?.ToLower() == "im" && rec.Too?.ToLower() == "im")
                {
                    amtReceived = rec.Amt_Received;
                }
                else if (rec.Frm?.ToLower() != "wm")
                {
                    amtReceived = rec.Quantity_Received;
                }

                qty += rec.Quantity;
                senttosap = rec.SENT_TO_SAP;
                TotalamtReceived += rec.Amt_Received;
                //itemStr += rec.Item_Nbr + "|" + rec.Matl_Nbr + "|" + rec.Ib_Raw_Mtls_Id + "|" + rec.Sap_Matl_Descr + "|" + rec.Quantity.ToString("#,##0.000") + "|" + rec.Amt_Received.ToString("#,##0.000") + "|" + rec.Requested_Delivery_Date?.ToShortDateString() + "|" + docType + "|" + rec.Uom + "~";
                itemStr += rec.Item_Nbr + "|" + rec.Matl_Nbr + "|" + rec.Ib_Raw_Mtls_Id + "|" + rec.Sap_Matl_Descr + "|" + rec.Quantity.ToString("#,##0.000") + "|" + (rec.Uom == "LB" ? KG_to_LB(amtReceived) : amtReceived).ToString("#,##0.000") + "|" + rec.Requested_Delivery_Date?.ToShortDateString() + "|" + docType + "|" + rec.Uom + "~";

                testNbr = rec.Document_Nbr;
            }

            var model = new RawMaterialsGroupedViewModel
            {
                PurchaseOrderList = modelList,
                TotalQTY = POList.Sum(p => p.Quantity)
            };

            return View(model);
        }

        [Route("RawMaterialReceivingSTO")]
        public IActionResult STO(string rmType)
        {
            ViewBag.TitlePart = "Stock Transfer Order";
            List<POMaterialModel> POList = _rawMaterialProcessor.GetInternalSTO();
            //POList = POList.FindAll(x => x.Delivery_No == "860136717");
            POList.Add(new POMaterialModel { Delivery_No = "" });   //for not missing last record   

            List<RawMaterialChildViewModel> modelList = new List<RawMaterialChildViewModel>();
            string testNbr = POList[0].Delivery_No;
            decimal qty = 0;
            string itemStr = "";
            long docNbr = 0;
            string supName = "";
            string supNo = "";
            string maDesc = "";
            string maType = "";
            string docType = "";
            string matTypeDesc = "";
            string matAdditionalInfo = "";
            decimal amtReceived = 0;
            decimal TotalamtReceived = 0;
            string deliveryNo = "";
            long ib_Raw_Mtls_Id = 0;
            int SENT_TO_SAP = 0;
            DateTime? deliveryDate = null;
            string ittmNbr = "";
            string po_closed = "";
            foreach (var rec in POList)
            {
                if (testNbr != rec.Delivery_No)
                {
                    RawMaterialChildViewModel childVM = new RawMaterialChildViewModel();
                    POMaterialModel po = new POMaterialModel();
                    po.Document_Nbr = docNbr;
                    po.Supplier_Name = supName;
                    po.Supplier_Nbr = supNo;
                    po.Quantity = qty;
                    po.Amt_Received = TotalamtReceived;
                    po.Sap_Matl_Descr = maDesc;
                    po.Sap_Matl_Type = maType;
                    po.Matl_type_descr = matTypeDesc;
                    po.Additional_info = matAdditionalInfo;
                    po.Document_Type = docType;
                    po.Requested_Delivery_Date = deliveryDate;
                    po.Delivery_No = deliveryNo;
                    po.Ib_Raw_Mtls_Id = ib_Raw_Mtls_Id;
                    po.Matl_Nbr = rec.Matl_Nbr;
                    po.Item_Nbr = rec.Item_Nbr;
                    po.SENT_TO_SAP = SENT_TO_SAP;
                    po.po_closed = po_closed;
                    po.Frm = rec.Frm;
                    po.Too = rec.Too;
                    po.Quantity_Received = rec.Quantity_Received;
                    //to-do:
                    //var stoChildren = _rawMaterialProcessor.GetSTOByMtrl_Nbr(rec.Matl_Nbr);

                    //itemStr += rec.Item_Nbr+".."+rec.Document_Nbr + "|" + rec.Matl_Nbr + "|" + rec.Ib_Raw_Mtls_Id + "|" + rec.Sap_Matl_Descr + "|" + rec.Quantity.ToString("#,##0") + "|" + rec.Amt_Received.ToString("#,##0") + "|" + rec.Requested_Delivery_Date?.ToShortDateString() + "|" + docType + "|" + rec.Uom + "|" + rec.storage_unit_nbr + "~";

                    childVM.POMaterial = po;
                    childVM.LineItems = itemStr;
                    modelList.Add(childVM);
                    qty = 0;
                    TotalamtReceived = 0;
                    itemStr = "";
                }

                docNbr = rec.Document_Nbr;
                supName = rec.Supplier_Name;
                supNo = rec.Supplier_Nbr;
                maDesc = rec.Sap_Matl_Descr;
                maType = rec.Sap_Matl_Type;
                docType = rec.Document_Type;
                matTypeDesc = rec.Matl_type_descr;
                matAdditionalInfo = rec.Additional_info;
                deliveryDate = rec.Requested_Delivery_Date;
                amtReceived = rec.Amt_Received;


                if (rec.Frm?.ToLower() == "im" && rec.Too?.ToLower() == "im")
                {
                    amtReceived = rec.Quantity_Received;
                }
                else if (rec.Frm?.ToLower() != "wm")
                {
                    amtReceived = rec.Amt_Received;
                }




                deliveryNo = rec.Delivery_No;
                ib_Raw_Mtls_Id = rec.Ib_Raw_Mtls_Id;
                SENT_TO_SAP = rec.SENT_TO_SAP;
                qty += rec.Quantity;
                TotalamtReceived += rec.Amt_Received;
                po_closed = rec.po_closed;
                //if (ittmNbr != rec.Item_Nbr.ToString())
                itemStr += rec.Item_Nbr + "|" + rec.Matl_Nbr + "|" + rec.Ib_Raw_Mtls_Id + "|" + rec.Sap_Matl_Descr + "|" + rec.Quantity.ToString("#,##0.000") + "|" + (rec.Uom == "LB" ? KG_to_LB(amtReceived) : amtReceived).ToString("#,##0.000") + "|" + rec.Requested_Delivery_Date?.ToShortDateString() + "|" + docType + "|" + rec.Uom + "|" + rec.storage_unit_nbr + "~";

                testNbr = rec.Delivery_No;

OldSourceCode/SmartMFGFoley/WebApp/Views/Shared/NotFound.cshtml
@model ErrorViewModel

@{
    ViewData["Title"] = "Not Found";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <h1 class="text-danger">Error.</h1>
    <div class="alert alert-danger">An error occurred while processing your request.</h2>
</div>

OldSourceCode/SmartMFGFoley/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SmartMFG Foley</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/fontawesome/fontawesome-all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/all.min.css" asp-append-version="true" />
    </environment>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<script>
    
    $(document).ready(function () {
        $('.filter-icon-con').click(function () {
            $(this).addClass('filter-icon-active')           
        })
       
        $(document).on('click touch', function (e) {
            if (!$(e.target).parents().addBack().is('.filter-icon-con')) {
                $('.filter-icon-con').removeClass('filter-icon-active');
                
            }
        })
        $(document).on('click touch', function (e) {
            if (!$(e.target).parents().addBack().is('.key-icon-con')) {
               
                $('#export-filters').hide();
                $('#export-filter-icon').show();
            }
        })
    })
</script>
<body>
    <header class="apm-header">
        @*<h1 id="navbarLogo" onclick="location.href='@Url.Action("Index", "InboundRawMaterials")';return false;"><span>smart</span>MFG - Suzhou</h1>*@
        <h1 id="navbarLogo" onclick="location.href='./';return false;"><span>smart</span>MFG - Foley</h1>

        <h1 id="navbarheader">@ViewData["Title"]</h1>

        @await Component.InvokeAsync("UserInfo")

    </header>
    <main role="main" class="mt-5">
        <div class="container-fluid">
            @RenderBody()
        </div>
    </main>
   
    <footer class="apm-footer">
        <p>SmartMFG &copy; @DateTime.Now.Year - Ascend Performance Materials</p>
        <p>Version 3.1.0</p>
    </footer>

    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="~/js/TypeAhead/bootstrap3-typeahead.min.js"></script>
    <script src="~/js/CountryDropDown/bootstrap-select-country.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

OldSourceCode/SmartMFGFoley/WebApp/Views/Shared/_NavLinks.cshtml
<div class="row pl-3">
    <div class="apm-icon-home" id="home-icon" onclick="location.href='@Url.Action("Index", "Home")';return false;">
        <i class="fa fa-home apm-icon"></i>
        <span>Home</span>
    </div>

    <div class="apm-icon-home" id="barcode-icon" onclick="location.href='@Url.Action("STO", "InboundRawMaterials")';return false;">
        <i class="fas fa-clipboard-list apm-icon"></i>
        <span>STO</span>
    </div>
    
    <div class="apm-icon-home" id="barcode-icon" onclick="location.href='@Url.Action("Index", "InboundRawMaterials", new { rmType = "Purchase_Order" })';return false;">
        <i class="fab fa-product-hunt apm-icon"></i>
        <span>Purchase Order</span>
    </div>
</div>

OldSourceCode/SmartMFGFoley/WebApp/Views/Shared/_NavLinksPopup.cshtml
<div class="row pl-3">
    <div class="apm-icon-home" id="home-icon" onclick="location.href='@Url.Action("Index", "Home")';return false;">
        <i class="fa fa-home apm-icon"></i>
        <span>Home</span>
    </div>
    <div class="apm-icon-home" >
       <a id="scanPO"><i class="fas fa-barcode apm-icon"></i></a>  
        <span>Scan Label</span>
    </div>
</div>